import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans'; // Correct import for GeistSans
import { GeistMono } from 'geist/font/mono'; // Correct import for GeistMono
import "./globals.css";
// import { Toaster } from "@/components/ui/sonner"; // Удаляем импорт Toaster

const geistSans = GeistSans; // Use directly
const geistMono = GeistMono; // Use directly

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen font-[family-name:var(--font-geist-sans)]`}
      >
        {children}
        {/* <Toaster /> */} {/* Удаляем Toaster */}
      </body>
    </html>
  );
}